spring:
  application:
    name: learn-spring-graphql

server:
  http2:
    enabled: true

graphql:
  servlet:
    max-query-depth: 5
    exception-handlers-enabled: false
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:graphql/playground/bank_account.graphql
        variables: classpath:graphql/playground/bank_account_variables.json
voyager:
  enabled: false
