spring:
  application:
    name: learn-spring-graphql
  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      url: mongodb://localhost:27017/tbsmpoc
      database: tbsmpoc

server:
  http2:
    enabled: true

graphql:
  servlet:
    max-query-depth: 5
    exception-handlers-enabled: false
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:graphql/playground/bank_account.graphql
        variables: classpath:graphql/playground/bank_account_variables.json
voyager:
  enabled: false

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
